_core:
  default_config_hash: xYr-CGwUzm83U6udcxQPhC2KPVFFWAVdyrd-tUiEwN4
api_build_status: NO_CONTENT
api_url: 'https://eu-api.sitestudio.acquia.com'
api_key: ivorylocust-30611
organization_key: axeleranttechnologiespvtltd-50778
site_id: 7837542c-ed2c-4dbb-ae07-ecd6ee7f6b6c
use_dx8: enable
google_map_api_key: ''
asset_is_imported: '1'
animate_on_view_mobile: DISABLED
elements_permissions: '{}'
sidebar_view_style: titles
log_dx8_error: disable
add_animation_classes: DISABLED
sync_legacy_visibility: false
element_toggle: '{"link":true,"list-container":true,"list-item":true,"inline-element":true,"container":true,"row-for-columns":true,"column":true,"iframe":true,"image":true,"picture":true,"video":true,"video-background":true,"youtube-video-embed":true,"youtube-video-background":true,"button":true,"slider-container":true,"slide":true,"accordion-tabs-container":true,"accordion-tabs-item":true,"google-map":true,"google-map-marker":true,"read-more":true,"modal":true,"drupal-view":true,"drupal-view-contents":true,"drupal-view-item":true,"drupal-view-variable":true,"pattern-repeater":true,"pagination":true,"drupal-view-filter":true,"drupal-view-filter-submit":true,"menu-list-container":true,"menu-list-item":true,"menu-link":true,"menu-button":true,"drupal-region":true,"drupal-block":true,"drupal-content":true,"drupal-menu":true,"drupal-field":true,"drupal-field-item":true,"breadcrumb":true,"entity-reference":true,"entity-browser":true,"wysiwyg":true,"heading":true,"paragraph":true,"blockquote":true}'
element_usage_last_run: 0
image_browser:
  config:
    type: imce_imagebrowser
    dx8_imce_stream_wrapper: public
  content:
    type: medialib_imagebrowser
    cohesion_media_lib_types:
      - image
      - '0'
      - '0'
      - '0'
      - '0'
